# Generated by Django 5.0.6 on 2026-08-01 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_attendance',
                'ordering': ['-date'],
                'unique_together': {('delivery_partner', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('bicycle', 'Bicycle'), ('bike', 'Motorbike/Scooter'), ('car', 'Car')], max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_online', models.BooleanField(default=False, help_text='Toggled by the delivery partner to receive orders')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_profiles',
                'indexes': [models.Index(fields=['status', 'is_online'], name='delivery_pr_status_1928ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('delivery_earning', 'Per-delivery earning'), ('incentive', 'Incentive / bonus'), ('payout', 'Payout to bank account'), ('adjustment', 'Manual adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive=earning, negative=payout/adjustment', max_digits=10)),
                ('order_reference', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delivery_partner', 'created_at'], name='delivery_tr_deliver_d431a0_idx')],
            },
        ),
    ]
