# Generated by Django 5.2.16 on 2026-08-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='aadhaar_image',
            field=models.ImageField(blank=True, help_text='Photo/scan of the Aadhaar card', null=True, upload_to='delivery_documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='license_image',
            field=models.ImageField(blank=True, help_text='Photo of the driving license', null=True, upload_to='delivery_documents/license/'),
        ),
    ]
