# Generated by Django 5.2.16 on 2026-08-06 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryprofile_aadhaar_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='aadhaar_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='aadhaar_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='current_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='license_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/license/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='license_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/license/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/pan/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/photos/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='selfie_photo',
            field=models.ImageField(blank=True, help_text='Live selfie for identity verification', null=True, upload_to='delivery_documents/photos/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='state',
            field=models.CharField(default='Jharkhand', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='vehicle_insurance_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/vehicle/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='vehicle_rc_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/vehicle/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='vehicle_rc_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='verification_status',
            field=models.CharField(choices=[('documents_submitted', 'Documents submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_required', 'Resubmission required')], default='documents_submitted', max_length=25),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/license/'),
        ),
        migrations.CreateModel(
            name='DeliveryVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission requested')], max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='delivery.deliveryprofile')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_verification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
