# Generated by Django 5.2.16 on 2026-08-08 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryprofile_aadhaar_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='aadhaar_back_image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_documents/aadhaar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='aadhaar_front_image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_documents/aadhaar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='aadhaar_image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_documents/aadhaar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='license_back_image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_documents/license/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='license_front_image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_documents/license/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='license_image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_documents/license/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='pan_card_image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_documents/pan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='vehicle_insurance_image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_documents/vehicle/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='vehicle_rc_image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_documents/vehicle/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
    ]
