# Generated by Django 5.2.16 on 2026-08-09 05:08

import apps.core.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_deliveryprofile_aadhaar_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='aadhaar_number',
            field=apps.core.encrypted_fields.EncryptedCharField(blank=True, help_text='12-digit Aadhaar number', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='pan_number',
            field=apps.core.encrypted_fields.EncryptedCharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryverificationlog',
            name='action',
            field=models.CharField(choices=[('marked_under_review', 'Marked under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission requested')], max_length=25),
        ),
    ]
