# Generated by Django 5.0.6 on 2026-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_otp',
            field=models.CharField(blank=True, help_text='Shown to the vendor; delivery partner enters this to confirm pickup from the shop', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, help_text='Shown to the customer; delivery partner enters this to confirm final delivery', max_length=6),
        ),
    ]
