# Generated by Django 5.2.16 on 2026-08-03 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pickup_otp_alter_order_delivery_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('cod', 'Cash on delivery'), ('razorpay', 'Razorpay (card/UPI/netbanking)')], max_length=20, unique=True)),
                ('label', models.CharField(blank=True, help_text='Override display label (optional)', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('extra_fee', models.DecimalField(decimal_places=2, default=0, help_text='e.g. COD handling fee', max_digits=8)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'payment_method_configs',
                'ordering': ['display_order'],
            },
        ),
    ]
