# Generated by Django 5.2.16 on 2026-08-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_method_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('razorpay', 'Razorpay (card/UPI/netbanking)'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='code',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('razorpay', 'Razorpay (card/UPI/netbanking)'), ('wallet', 'Wallet')], max_length=20, unique=True),
        ),
    ]
