# Generated by Django 5.2.17 on 2026-09-07 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Internal key, e.g. handling / packing / night / rain', max_length=40, unique=True)),
                ('label', models.CharField(help_text="Shown to the customer, e.g. 'Packing charge'", max_length=100)),
                ('charge_type', models.CharField(choices=[('flat', 'Flat amount'), ('percent', 'Percentage of subtotal')], default='flat', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rupees for flat, or percent for percentage', max_digits=8)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage charges (ignored for flat)', max_digits=8, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Only apply when the order subtotal is at least this', max_digits=10, null=True)),
                ('active_from_hour', models.PositiveSmallIntegerField(blank=True, help_text='0–23. Start of the hours this applies (e.g. 22 for a night charge). Blank = any time', null=True)),
                ('active_to_hour', models.PositiveSmallIntegerField(blank=True, help_text='0–23. End hour (exclusive). May wrap past midnight, e.g. from 22 to 6', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Master switch — a rain charge is simply toggled on when it's raining")),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extra_charges',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='extra_charges_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='List of {code, label, amount} for each extra charge applied, snapshotted at order time'),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_charges_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of admin-configured extra charges (handling/packing/night/rain) applied to this order', max_digits=10),
        ),
    ]
