[pytest]
DJANGO_SETTINGS_MODULE = mall_of_garhwa.settings.test
python_files = test_*.py
addopts = --reuse-db --nomigrations -v
testpaths = apps

[coverage:run]
omit =
    */migrations/*
    */tests/*
    manage.py
    */settings/*
    */asgi.py
    */wsgi.py
