# Generated by Django 5.0.6 on 2026-08-01 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit for this batch', max_digits=10)),
                ('supplier_name', models.CharField(blank=True, max_length=150)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank for non-perishables (electronics, clothing)', null=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='catalog.product')),
            ],
            options={
                'db_table': 'stock_batches',
                'ordering': ['expiry_date', '-created_at'],
                'indexes': [models.Index(fields=['product', 'expiry_date'], name='stock_batch_product_f4c4ad_idx')],
            },
        ),
    ]
