# Generated by Django 5.2.16 on 2026-08-03 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_variants_attributes'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase (batch received)'), ('sale', 'Sale'), ('return', 'Return / cancellation'), ('adjustment', 'Manual adjustment')], max_length=12)),
                ('quantity_delta', models.IntegerField(help_text='Positive = stock added, negative = stock removed')),
                ('resulting_stock', models.PositiveIntegerField(help_text='Product.stock_quantity right after this movement')),
                ('reference', models.CharField(blank=True, help_text='e.g. order number or batch number', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'movement_type'], name='stock_movem_product_1c9b03_idx')],
            },
        ),
    ]
