# Generated by Django 5.2.16 on 2026-08-04 23:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_movement'),
        ('vendors', '0003_vendor_city_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Main shop', 'Cold storage', 'Backup godown'", max_length=100)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_warehouses',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Optional — which physical location this batch is stored at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='inventory.vendorwarehouse'),
        ),
        migrations.AddConstraint(
            model_name='vendorwarehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('vendor',), name='one_default_vendor_warehouse'),
        ),
    ]
