# Generated by Django 5.2.16 on 2026-08-05 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('superadmin', '0003_platformsettings_delivery_free_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('post_facebook', models.BooleanField(default=False)),
                ('post_instagram', models.BooleanField(default=False)),
                ('audience', models.CharField(choices=[('all_customers', 'All customers'), ('city', 'Customers in a specific city'), ('recent_buyers', 'Ordered in the last 30 days'), ('inactive', 'No order in the last 60 days (win-back)')], default='all_customers', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Email subject line', max_length=200)),
                ('message', models.TextField(help_text='Body text — used for email/SMS/WhatsApp and as the social caption')),
                ('image', models.ImageField(blank=True, help_text='Used for email header + Facebook/Instagram posts', null=True, upload_to='campaigns/')),
                ('link_url', models.URLField(blank=True, help_text='Optional — included in email/social posts')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Leave blank to send immediately', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('partially_sent', 'Partially sent (some channels/recipients failed)'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('facebook_post_id', models.CharField(blank=True, max_length=100)),
                ('facebook_error', models.CharField(blank=True, max_length=500)),
                ('instagram_post_id', models.CharField(blank=True, max_length=100)),
                ('instagram_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('audience_city', models.ForeignKey(blank=True, help_text="Only used when audience='city'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (no email/phone on file)')], default='pending', max_length=10)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_recipients',
                'indexes': [models.Index(fields=['campaign', 'channel', 'status'], name='campaign_re_campaig_1a88bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'user', 'channel'), name='unique_campaign_user_channel')],
            },
        ),
    ]
