# Generated by Django 5.2.16 on 2026-08-05 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campaign_campaignrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='selected_customers',
            field=models.ManyToManyField(blank=True, help_text="Only used when audience='selected' — individually hand-picked recipients", related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='audience',
            field=models.CharField(choices=[('all_customers', 'All customers'), ('city', 'Customers in a specific city'), ('recent_buyers', 'Ordered in the last 30 days'), ('inactive', 'No order in the last 60 days (win-back)'), ('selected', 'Hand-picked customers')], default='all_customers', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignExternalContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (no email/phone on file)')], default='pending', max_length=10)),
                ('whatsapp_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (no email/phone on file)')], default='pending', max_length=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_contacts', to='marketing.campaign')),
            ],
            options={
                'db_table': 'campaign_external_contacts',
            },
        ),
    ]
