# Generated by Django 5.2.16 on 2026-08-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_variants_attributes'),
        ('marketing', '0003_campaign_selected_customers_alter_campaign_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Auto-drafted when a vendor published a new product'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='source_product',
            field=models.ForeignKey(blank=True, help_text='The product this campaign was auto-drafted for, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product'),
        ),
    ]
