# Generated by Django 5.2.16 on 2026-08-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='referral_bonus_referred',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Wallet credit for the new signup', max_digits=8),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='referral_bonus_referrer',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Wallet credit for the person who referred', max_digits=8),
        ),
    ]
