# Generated by Django 5.2.16 on 2026-08-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_platformsettings_referral_bonus_referred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='delivery_free_km',
            field=models.DecimalField(decimal_places=2, default=3, help_text='Distance covered by the base charge before per-km pricing kicks in', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='delivery_per_km_charge',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Extra charge per km beyond delivery_free_km', max_digits=6),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='max_delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Orders from vendors beyond this distance are blocked at checkout', max_digits=5),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='default_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=25, help_text='Base charge, covers the first delivery_free_km', max_digits=6),
        ),
    ]
