# Generated by Django 5.2.17 on 2026-09-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_platformsettings_delivery_free_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermission',
            name='department',
            field=models.CharField(choices=[('custom', 'Custom (pick sections manually)'), ('full', 'Full access'), ('accounts', 'Accounts / Finance'), ('vendor_desk', 'Vendor desk'), ('delivery_desk', 'Delivery desk'), ('catalog', 'Catalog / Products'), ('support', 'Customer support')], default='custom', help_text="Pick a department to auto-set the sections below, or 'Custom' to choose them yourself", max_length=20),
        ),
    ]
