# Generated by Django 5.0.6 on 2026-07-31 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('grocery', 'Grocery'), ('fruits_vegetables', 'Fruits & vegetables'), ('medical', 'Medical'), ('bakery', 'Bakery'), ('meat', 'Meat'), ('electronics', 'Electronics'), ('clothing', 'Clothing')], max_length=30)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(default='Garhwa', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendors',
                'indexes': [models.Index(fields=['category', 'status'], name='vendors_categor_c13879_idx')],
            },
        ),
    ]
