# Generated by Django 5.0.6 on 2026-08-01 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'Credit (order settlement)'), ('commission', 'Platform commission'), ('payout', 'Payout to vendor bank account'), ('adjustment', 'Manual adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive for credits, negative for commission/payout/adjustment-debits', max_digits=10)),
                ('order_reference', models.CharField(blank=True, help_text='Order number, once orders exist', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'type', 'created_at'], name='vendor_tran_vendor__bc9f56_idx')],
            },
        ),
    ]
