# Generated by Django 5.0.6 on 2026-08-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('vendors', '0002_vendortransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='city_ref',
            field=models.ForeignKey(blank=True, help_text='Optional link to the managed City registry, for city-level delivery pricing overrides', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='superadmin.city'),
        ),
    ]
