# Generated by Django 5.2.16 on 2026-08-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_city_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gst_certificate',
            field=models.ImageField(blank=True, help_text='Photo/scan of the GST registration certificate', null=True, upload_to='vendor_documents/gst/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_document',
            field=models.ImageField(blank=True, help_text='Shop license, trade registration, or other proof-of-business document', null=True, upload_to='vendor_documents/shop/'),
        ),
    ]
