# Generated by Django 5.2.16 on 2026-08-06 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_gst_certificate_vendor_shop_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_name',
            field=models.CharField(blank=True, help_text='Legal/registered business name, if different from the shop name', max_length=150),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_registration_document',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_documents/business_reg/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole proprietorship'), ('partnership', 'Partnership'), ('private_limited', 'Private limited company'), ('llp', 'LLP'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cancelled_cheque',
            field=models.ImageField(blank=True, help_text='Cancelled cheque or other bank proof', null=True, upload_to='vendor_documents/bank/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fssai_license_document',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_documents/fssai/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fssai_license_number',
            field=models.CharField(blank=True, help_text='Required for food businesses', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_documents/owner/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_documents/pan/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_documents/shop_photos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_interior_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_documents/shop_photos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(default='Jharkhand', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='verification_status',
            field=models.CharField(choices=[('documents_submitted', 'Documents submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_required', 'Resubmission required')], default='documents_submitted', max_length=25),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='years_in_business',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_documents/gst/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_document',
            field=models.ImageField(blank=True, help_text='Shop license / trade registration proof', null=True, upload_to='vendor_documents/shop/'),
        ),
        migrations.CreateModel(
            name='VendorVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission requested')], max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_verification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
