# Generated by Django 5.2.16 on 2026-08-08 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_aadhaar_card_vendor_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/aadhaar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_registration_document',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/business_reg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cancelled_cheque',
            field=models.FileField(blank=True, help_text='Cancelled cheque or other bank proof', null=True, upload_to='vendor_documents/bank/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fssai_license_document',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/fssai/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/gst/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/pan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_document',
            field=models.FileField(blank=True, help_text='Shop license / trade registration proof', null=True, upload_to='vendor_documents/shop/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
    ]
