# Generated by Django 5.2.16 on 2026-08-09 05:08

import apps.core.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendor_aadhaar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='bank_account_number',
            field=apps.core.encrypted_fields.EncryptedCharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_number',
            field=apps.core.encrypted_fields.EncryptedCharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorverificationlog',
            name='action',
            field=models.CharField(choices=[('marked_under_review', 'Marked under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission requested')], max_length=25),
        ),
    ]
