# Generated by Django 5.0.6 on 2026-08-01 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(unique=True)),
                ('summary_text', models.TextField()),
                ('raw_data', models.JSONField(help_text='The aggregates that were sent to the AI model')),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
