# Generated by Django 6.0.7 on 2026-08-03 03:59
import uuid

from django.db import migrations, models


def dedupe_product_slugs(apps, schema_editor):
    """
    Before this migration, Product.slug had no uniqueness guarantee, so two
    vendors selling a same-named product (e.g. "Amul Milk 500ml") could end
    up with identical slugs. Give every duplicate but the first a unique
    suffix before the AlterField below enforces uniqueness at the DB level.
    """
    Product = apps.get_model("catalog", "Product")
    seen = set()
    for product in Product.objects.all().order_by("created_at"):
        slug = product.slug
        if slug and slug not in seen:
            seen.add(slug)
            continue
        base = slug or "product"
        new_slug = f"{base}-{uuid.uuid4().hex[:6]}"
        while new_slug in seen or Product.objects.filter(slug=new_slug).exists():
            new_slug = f"{base}-{uuid.uuid4().hex[:6]}"
        product.slug = new_slug
        product.save(update_fields=["slug"])
        seen.add(new_slug)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_product_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
