# Generated by Django 5.2.16 on 2026-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_variants_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_or_marketer',
            field=models.CharField(blank=True, help_text="Legal manufacturer/marketer name for the 'Information' card", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, help_text="e.g. '24 months', '6 months' — leave blank for non-perishables", max_length=50),
        ),
    ]
