# Generated by Django 5.2.16 on 2026-08-04 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_media_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(help_text='Images or PDFs only', upload_to='media_library/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif', 'pdf'])]),
        ),
    ]
