# Generated by Django 5.0.6 on 2026-08-01 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('order', 'Order update'), ('promo', 'Promotion / offer'), ('system', 'System'), ('vendor', 'Vendor alert'), ('delivery', 'Delivery alert')], default='system', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, help_text="Extra payload, e.g. {'order_id': '...'}", null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
